INSERT INTO HEROES (
    ID_HERO,
    "name",
    ID_GAME,
    "description",
    PRIMARY_ATTR,
    ATTACK_TYPE,
    ROLES,
    BASE_HEALTH,
    BASE_HEALTH_REGEN,
    BASE_MANA,
    BASE_MANA_REGEN,
    BASE_ARMOR,
    BASE_MR,
    BASE_ATTACK_MIN,
    BASE_ATTACK_MAX,
    BASE_STR,
    BASE_AGI,
    BASE_INT,
    STR_GAIN,
    AGI_GAIN,
    INT_GAIN,
    ATTACK_RANGE,
    PROJECTILE_SPEED,
    ATTACK_RATE,
    BASE_ATTACK_TIME,
    ATTACK_POINT,
    MOVE_SPEED,
    TURN_RATE,
    CM_ENABLED,
    LEGS,
    DAY_VISION,
    NIGHT_VISION,
    LOCALIZED_NAME
) VALUES (
    {{ ID_HERO }},
    '{{ NAME }}',
    {{ ID_GAME }},
    '{{ DESCRIPTION }}',
    '{{ PRIMARY_ATTR }}',
    '{{ ATTACK_TYPE }}',
    ARRAY[{{ ROLES }}],
    {{ BASE_HEALTH }},
    {{ BASE_HEALTH_REGEN }},
    {{ BASE_MANA }},
    {{ BASE_MANA_REGEN }},
    {{ BASE_ARMOR }},
    {{ BASE_MR }},
    {{ BASE_ATTACK_MIN }},
    {{ BASE_ATTACK_MAX }}, 
    {{ BASE_STR }},
    {{ BASE_AGI }},
    {{ BASE_INT }},
    {{ STR_GAIN }},
    {{ AGI_GAIN }},
    {{ INT_GAIN }},
    {{ ATTACK_RANGE }},
    {{ PROJECTILE_SPEED }},
    {{ ATTACK_RATE }},
    {{ BASE_ATTACK_TIME }},
    {{ ATTACK_POINT }},
    {{ MOVE_SPEED }},
    {{ TURN_RATE }},
    {{ CM_ENABLED }},
    {{ LEGS }},
    {{ DAY_VISION }},
    {{ NIGHT_VISION }},
    '{{ LOCALIZED_NAME }}'
)
