INSERT INTO PROPLAYERS (
    ID_ACCOUNT,
    NAME,
    DESCRIPTION,
    REGISTER_DATE
) VALUES (
    {{ ID_ACCOUNT }},
    '{{ NAME }}',
    '{{ DESCRIPTION }}',
    DEFAULT
)
ON CONFLICT (ID_ACCOUNT) DO UPDATE SET
    NAME            = COALESCE(EXCLUDED.NAME, PROPLAYERS.NAME),
    DESCRIPTION     = COALESCE(EXCLUDED.DESCRIPTION, PROPLAYERS.DESCRIPTION),
    REGISTER_DATE   = COALESCE(EXCLUDED.REGISTER_DATE, PROPLAYERS.REGISTER_DATE)



