INSERT INTO PLAYLIST_MOVIE (
    ID_VIDEO,
    URL,
    ID_PLAYLIST,
    ID_GAME,
    ID_PROPLAYER,
    ID_HERO,
    REGISTER_DATE
) VALUES (
    '{{ ID_VIDEO }}',
    '{{ URL }}',
    '{{ ID_PLAYLIST }}',
    '{{ ID_GAME }}',
    '{{ ID_PROPLAYER }}',
    '{{ ID_HERO }}',
    '{{ REGISTER_DATE }}'
)
ON CONFLICT (ID_VIDEO) DO UPDATE SET
    URL = COALESCE(PLAYLIST_MOVIE.URL, EXCLUDED.URL),
    ID_PLAYLIST = COALESCE(PLAYLIST_MOVIE.ID_PLAYLIST, EXCLUDED.ID_PLAYLIST),
    ID_GAME = COALESCE(PLAYLIST_MOVIE.ID_GAME, EXCLUDED.ID_GAME),
    ID_PROPLAYER = COALESCE(PLAYLIST_MOVIE.ID_PROPLAYER, EXCLUDED.ID_PROPLAYER),
    ID_HERO = COALESCE(PLAYLIST_MOVIE.ID_HERO, EXCLUDED.ID_HERO),
    REGISTER_DATE = COALESCE(PLAYLIST_MOVIE.REGISTER_DATE, EXCLUDED.REGISTER_DATE);
