INSERT INTO PLAYLIST_MOVIE_HISTORIC (
    ID_MOVIE,
    TITLE,
    "description",
    VIEWS,
    LIKES,
    LIVE,
    keywords,
    available_countries,
    CATEGORY,
    FAMILY_FRIENDLY,
    DT_UPLOAD,
    DT_PUBLISH,
    DT_START,
    DT_END
) VALUES (
    {{ ID_MOVIE }},
    '{{ TITLE }}',
    '{{ DESCRIPTION }}',
    {{ VIEWS }},
    {{ LIKES }},
    {{ LIVE }},
    ARRAY[{{ KEYWORDS }}],
    ARRAY[{{ AVAILABLE_COUNTRIES }}],
    '{{ CATEGORY }}',
    '{{ FAMILY_FRIENDLY }}',
    '{{ DT_UPLOAD }}',
    '{{ DT_PUBLISH }}',
    '{{ DT_START }}',
    '{{ DT_END }}'
)
ON CONFLICT (ID_MOVIE, DT_END) DO UPDATE SET
    TITLE = CASE 
        WHEN EXCLUDED.TITLE IS NOT NULL AND TRIM(EXCLUDED.TITLE) != '' 
        THEN EXCLUDED.TITLE 
        ELSE PLAYLIST_MOVIE_HISTORIC.TITLE 
    END,
    "description" = CASE 
        WHEN EXCLUDED."description" IS NOT NULL AND TRIM(EXCLUDED."description") != '' 
        THEN EXCLUDED."description" 
        ELSE PLAYLIST_MOVIE_HISTORIC."description" 
    END,
    VIEWS = CASE 
        WHEN EXCLUDED.VIEWS IS NOT NULL 
        THEN EXCLUDED.VIEWS 
        ELSE PLAYLIST_MOVIE_HISTORIC.VIEWS 
    END,
    LIKES = CASE 
        WHEN EXCLUDED.LIKES IS NOT NULL 
        THEN EXCLUDED.LIKES 
        ELSE PLAYLIST_MOVIE_HISTORIC.LIKES 
    END,
    LIVE = CASE 
        WHEN EXCLUDED.LIVE IS NOT NULL 
        THEN EXCLUDED.LIVE 
        ELSE PLAYLIST_MOVIE_HISTORIC.LIVE 
    END,
    keywords = CASE 
        WHEN EXCLUDED.keywords IS NOT NULL AND array_length(EXCLUDED.keywords, 1) > 0 
        THEN EXCLUDED.keywords 
        ELSE PLAYLIST_MOVIE_HISTORIC.keywords 
    END,
    available_countries = CASE 
        WHEN EXCLUDED.available_countries IS NOT NULL AND array_length(EXCLUDED.available_countries, 1) > 0 
        THEN EXCLUDED.available_countries 
        ELSE PLAYLIST_MOVIE_HISTORIC.available_countries 
    END,
    CATEGORY = CASE 
        WHEN EXCLUDED.CATEGORY IS NOT NULL AND TRIM(EXCLUDED.CATEGORY) != '' 
        THEN EXCLUDED.CATEGORY 
        ELSE PLAYLIST_MOVIE_HISTORIC.CATEGORY 
    END,
    FAMILY_FRIENDLY = CASE 
        WHEN EXCLUDED.FAMILY_FRIENDLY IS NOT NULL 
        THEN EXCLUDED.FAMILY_FRIENDLY 
        ELSE PLAYLIST_MOVIE_HISTORIC.FAMILY_FRIENDLY 
    END,
    DT_UPLOAD = CASE 
        WHEN EXCLUDED.DT_UPLOAD IS NOT NULL 
        THEN EXCLUDED.DT_UPLOAD 
        ELSE PLAYLIST_MOVIE_HISTORIC.DT_UPLOAD 
    END,
    DT_PUBLISH = CASE 
        WHEN EXCLUDED.DT_PUBLISH IS NOT NULL 
        THEN EXCLUDED.DT_PUBLISH 
        ELSE PLAYLIST_MOVIE_HISTORIC.DT_PUBLISH 
    END,
    DT_START = CASE 
        WHEN EXCLUDED.DT_START IS NOT NULL 
        THEN EXCLUDED.DT_START 
        ELSE PLAYLIST_MOVIE_HISTORIC.DT_START 
    END,
    DT_END = CASE 
        WHEN EXCLUDED.DT_END IS NOT NULL 
        THEN EXCLUDED.DT_END 
        ELSE PLAYLIST_MOVIE_HISTORIC.DT_END 
    END