CREATE TABLE IF NOT EXISTS CHANNEL_GAMES (
    ID_CHANNEL INTEGER NOT NULL,
    ID_GAME INTEGER NOT NULL,
    CONSTRAINT fk_channelgames_channel FOREIGN KEY (ID_CHANNEL) REFERENCES CHANNEL(ID_CHANNEL),
    CONSTRAINT fk_channelgames_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_CHANNEL, ID_GAME)
);
