CREATE TABLE IF NOT EXISTS ITENS_IMAGES (
    ID_ITEM INTEGER NOT NULL,
    "image" BYTEA,
    CONSTRAINT fk_itensimages_item FOREIGN KEY (ID_ITEM) REFERENCES ITENS(ID_ITEM),
    PRIMARY KEY (ID_ITEM)
);
