-- TABELA DE MUNICIPIOS EXPORTADORES
CREATE TABLE IF NOT EXISTS TEAMS_GAME (
    FOREIGN KEY (ID_TEAM) REFERENCES TEAMS(ID_TEAM),
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME),
    BANNER BLOB,
    PRIMARY KEY (ID_TEAM, ID_GAME)
);