CREATE TABLE IF NOT EXISTS PLAYLIST (
    ID_PLAYLIST INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "DESCRIPTION" VARCHAR(1000),
    FOREIGN KEY (ID_CHANNEL) REFERENCES CHANNEL(ID_CHANNEL) NOT NULL,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME) NOT NULL,
    "DATE" DATE NOT NULL,
    PRIMARY KEY ("NAME", ID_CHANNEL, ID_GAME)
);
