CREATE TABLE IF NOT EXISTS ITENS (
    ID_ITEM INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "DESCRIPTION" VARCHAR(1000),
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME),
    "VALUE" INTEGER NOT NULL,
    "IMAGE" BLOB,
    PRIMARY KEY (NAME, GAME)
);
