CREATE TABLE IF NOT EXISTS PROPLAYERS_HEROES (
    FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER) NOT NULL,
    FOREIGN KEY (ID_HERO) REFERENCES HEROES(ID_HERO) NOT NULL,
    FOREIGN KEY (ID_ITEM_1) REFERENCES ITENS(ID_ITEM),
    FOREIGN KEY (ID_ITEM_2) REFERENCES ITENS(ID_ITEM),
    FOREIGN KEY (ID_ITEM_3) REFERENCES ITENS(ID_ITEM),
    FOREIGN KEY (ID_ITEM_4) REFERENCES ITENS(ID_ITEM),
    FOREIGN KEY (ID_ITEM_5) REFERENCES ITENS(ID_ITEM),
    FOREIGN KEY (ID_ITEM_6) REFERENCES ITENS(ID_ITEM),
    FOREIGN KEY (ID_ITEM_7) REFERENCES ITENS(ID_ITEM),
    FOREIGN KEY (ID_ITEM_8) REFERENCES ITENS(ID_ITEM),
    FOREIGN KEY (ID_ITEM_9) REFERENCES ITENS(ID_ITEM),
    "DATE" DATE NOT NULL,
    PRIMARY KEY (ID_PROPLAYER, ID_HERO)
);
