CREATE TABLE IF NOT EXISTS PLAYLIST_MOVIE_HISTORIC (
    FOREIGN KEY (ID_MOVIE) REFERENCES PLAYLIST_MOVIE(ID_MOVIE) NOT NULL,
    "TITULO" VARCHAR(50) NOT NULL,
    "DESCRIPTION" VARCHAR(1000),
    LIKES INTEGER NOT NULL,
    "DATE_START" DATE NOT NULL,
    "DATE_END" DATE,
    PRIMARY KEY (ID_MOVIE, "DATE"),
);
