CREATE TABLE IF NOT EXISTS PROPLAYERS_HEROES (
    FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER) NOT NULL,
    FOREIGN KEY (ID_HERO) REFERENCES HEROES(ID_HERO) NOT NULL,
    "DATE" DATE NOT NULL,
    PRIMARY KEY (ID_PROPLAYER, ID_HERO)
);
