CREATE TABLE IF NOT EXISTS CHANNEL_GAMES (
    FOREIGN KEY (ID_CHANNEL) REFERENCES CHANNEL(ID_CHANNEL) NOT NULL,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME) NOT NULL,
    PRIMARY KEY (ID_CHANNEL, ID_GAME) NOT NULL
);
