CREATE TABLE IF NOT EXISTS CHANNEL (
    ID_CHANNEL SERIAL,
    "name" VARCHAR(50) NOT NULL,
    NAME2 VARCHAR(50) NOT NULL,
    NAME_VIEW VARCHAR(50) NOT NULL,
    ID_GAME INTEGER NOT NULL,
    LINK VARCHAR(200) NOT NULL,
    "description" VARCHAR(1000),
    LINK_FACE VARCHAR(200),
    LINK_INSTA VARCHAR(200),
    COUNTRY VARCHAR(30) NOT NULL,
    REGISTER_DATE DATE,
    BANNER BYTEA,
    CONSTRAINT fk_channel_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_CHANNEL)
);
