CREATE TABLE IF NOT EXISTS EVENTS (
    ID_EVENT SERIAL PRIMARY KEY,
    "name" VARCHAR(50) NOT NULL,
    ID_GAME INTEGER NOT NULL,
    DATE_START DATE,
    DATE_END DATE,
    CONSTRAINT fk_events_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME)
);
