CREATE TABLE IF NOT EXISTS EVENTS (
    ID_EVENT INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME),
    DATE_START DATE,
    DATE_END DATE,
    PRIMARY KEY (LINK)
);
