CREATE TABLE IF NOT EXISTS PROPLAYERS_IMAGES (
    FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER) NOT NULL,
    HASH_TUMBLR VARCHAR(64) NOT NULL,
    "IMAGE" BLOB,
    PRIMARY KEY (ID_PROPLAYER, HASH_TUMBLR)
);
