CREATE TABLE IF NOT EXISTS GROWTH_CHANNEL (
    CHANNEL VARCHAR(50) NOT NULL,
    VIEWS INTEGER NOT NULL,
    SUBSCRIBERS INTEGER NOT NULL,
    FOREIGN KEY (GAME) REFERENCES GAME(ID_GAME),
    "DATE" DATE,
    PRIMARY KEY (LINK)
);
