CREATE TABLE IF NOT EXISTS HEROES (
    ID_HERO INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME),
    "DESCRIPTION" VARCHAR(1000),
    "IMAGE" BLOB,
    PRIMARY KEY (NAME, GAME)
);
