CREATE TABLE IF NOT EXISTS PLAYLIST (
    ID_PLAYLIST SERIAL,
    ID_CHANNEL INTEGER NOT NULL,
    ID_GAME INTEGER NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "description" VARCHAR(1000),
    "date" DATE NOT NULL,
    CONSTRAINT fk_playlist_channel FOREIGN KEY (ID_CHANNEL) REFERENCES CHANNEL(ID_CHANNEL),
    CONSTRAINT fk_playlist_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_PLAYLIST)
);
