CREATE TABLE IF NOT EXISTS PROPLAYERS_IMAGES (
    ID_PROPLAYER INTEGER NOT NULL,
    HASH_TUMBLR VARCHAR(64) NOT NULL,
    "image" BYTEA,
    CONSTRAINT fk_proplayersimages_proplayer FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER),
    PRIMARY KEY (ID_PROPLAYER, HASH_TUMBLR)
);
