CREATE TABLE IF NOT EXISTS TUMBLR (
    "DESCRIPTION" VARCHAR(1000),
    FOREIGN KEY (ID_HERO) REFERENCES HEROES(ID_HERO),
    HASH_TUMBLR VARCHAR(64) NOT NULL,
    "IMAGE" BLOB,
    PRIMARY KEY (ID_HERO, HASH_TUMBLR)
);