CREATE TABLE IF NOT EXISTS PROPLAYERS_GAMES (
    FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER) NOT NULL,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME) NOT NULL,
    "DATE" DATE NOT NULL,
    PRIMARY KEY (ID_PROPLAYER, ID_GAME)
);
