CREATE TABLE IF NOT EXISTS PLAYLIST_MOVIE (
    ID_MOVIE INT AUTO_INCREMENT NOT NULL,
    ID_VIDEO VARCHAR(50) NOT NULL,
    "LINK" VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_CHANNEL) REFERENCES CHANNEL(ID_CHANNEL) NOT NULL,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME) NOT NULL,
    FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER) NOT NULL,
    FOREIGN KEY (ID_HERO) REFERENCES HEROES(ID_HERO) NOT NULL,
    TIME_MOVIE INTEGER NOT NULL,
    "DATE" DATE NOT NULL,
);
