CREATE TABLE IF NOT EXISTS CHANNEL (
    ID_CHANNEL INT AUTO_INCREMENT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    NAME2 VARCHAR(50) NOT NULL,
    NAME_VIEW VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_GAME) REFERENCES GAME(ID_GAME) NOT NULL,
    LINK VARCHAR(200) NOT NULL,
    "DESCRIPTION" VARCHAR(1000),
    LINK_FACE VARCHAR(200),
    LINK_INSTA VARCHAR(200),
    COUNTRY VARCHAR(30) NOT NULL,
    REGISTER_DATE DATE,
    BANNER BLOB,
    PRIMARY KEY (LINK)
);
