CREATE TABLE IF NOT EXISTS PLAYLIST_MOVIE_TUMBLR (
    FOREIGN KEY (ID_MOVIE) REFERENCES PLAYLIST_MOVIE(ID_MOVIE) NOT NULL,
    HASH_TUMBLR VARCHAR(64) NOT NULL,
    TUMBLR BLOB NOT NULL,
    "DATE" DATE NOT NULL,
    PRIMARY KEY (HASH_TUMBLR)
);
