CREATE TABLE IF NOT EXISTS CHANNEL_HISTORIC (
    FOREIGN KEY (ID_CHANNEL) REFERENCES CHANNEL(ID_CHANNEL) NOT NULL,
    VIEWS INTEGER NOT NULL,
    SUBSCRIBERS INTEGER NOT NULL,
    "DATE" DATE NOT NULL,
    PRIMARY KEY (ID_CHANNEL, "DATE")
);
