CREATE TABLE IF NOT EXISTS CHANNEL_HISTORIC (
    ID_CHANNEL INTEGER NOT NULL,
    VIEWS INTEGER NOT NULL,
    SUBSCRIBERS INTEGER NOT NULL,
    "date" DATE NOT NULL,
    CONSTRAINT fk_channelhistoric_channel FOREIGN KEY (ID_CHANNEL) REFERENCES CHANNEL(ID_CHANNEL),
    PRIMARY KEY (ID_CHANNEL, "date")
);
