-- TABELA DE MUNICIPIOS EXPORTADORES
CREATE TABLE IF NOT EXISTS CHANNEL (
    NAME VARCHAR(50) NOT NULL,
    NAME2 VARCHAR(50) NOT NULL,
    GAME VARCHAR(50) NOT NULL,
    LINK VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    LINK_FACE VARCHAR(200) NOT NULL,
    LINK_INSTA VARCHAR(200) NOT NULL,
    COUNTRY VARCHAR(30),
    REGISTER_DATE DATE,
    PRIMARY KEY (LINK)
);
