CREATE TABLE IF NOT EXISTS PLAYLIST_MOVIE_HISTORIC (
    ID_MOVIE INTEGER NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    "description" VARCHAR(1000),
    LIKES INTEGER NOT NULL,
    DT_START DATE NOT NULL,
    DT_END DATE,
    CONSTRAINT fk_playlistmoviehistoric_movie FOREIGN KEY (ID_MOVIE) REFERENCES PLAYLIST_MOVIE(ID_MOVIE),
    PRIMARY KEY (ID_MOVIE, DT_END)
);