CREATE TABLE IF NOT EXISTS CHANNEL_GAMES (
    ID_YOUTUBE VARCHAR(30) NOT NULL,
    ID_GAME INTEGER NOT NULL,
    CONSTRAINT fk_channelgames_channel FOREIGN KEY (ID_YOUTUBE) REFERENCES CHANNEL(ID_YOUTUBE),
    CONSTRAINT fk_channelgames_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_YOUTUBE, ID_GAME)
);
