CREATE TABLE IF NOT EXISTS PLAYLIST_MOVIE_TUMBLR (
    ID_MOVIE INTEGER NOT NULL,
    HASH_TUMBLR VARCHAR(64) NOT NULL,
    TUMBLR BYTEA NOT NULL,
    REGISTER_DATE DATE NOT NULL,
    CONSTRAINT fk_playlistmovietumblr_movie FOREIGN KEY (ID_MOVIE) REFERENCES PLAYLIST_MOVIE(ID_MOVIE),
    PRIMARY KEY (HASH_TUMBLR)
);

