CREATE TABLE IF NOT EXISTS CHANNEL (
    ID_CHANNEL SERIAL,
    ID_YOUTUBE VARCHAR(30) NOT NULL,
    URL VARCHAR(100) NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    DESCRIPTION_SNIPPET VARCHAR(300),
    HANDLE_NAME VARCHAR(50) NOT NULL,
    HANDLE VARCHAR(50) NOT NULL,
    ID_GAME INTEGER,
    COUNTRY VARCHAR(30),
    REGISTER_DATE DATE,
    MY_CHANNEL BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_channel_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_YOUTUBE)
);