CREATE TABLE IF NOT EXISTS PLAYLIST_MOVIE (
    ID_MOVIE SERIAL PRIMARY KEY,
    ID_VIDEO VARCHAR(50) NOT NULL,
    URL VARCHAR(100) NOT NULL,
    ID_PLAYLIST VARCHAR(50) NOT NULL,
    ID_GAME INTEGER,
    ID_PROPLAYER INTEGER,
    ID_HERO INTEGER,
    --TIME_MOVIE INTEGER NOT NULL,
    --PUBLISHED_DATE VARCHAR(20) NOT NULL,
    REGISTER_DATE DATE NOT NULL,
    CONSTRAINT fk_playlistmovie_playlist FOREIGN KEY (ID_PLAYLIST) REFERENCES PLAYLIST(ID_PLAYLIST),
    CONSTRAINT fk_playlistmovie_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    CONSTRAINT fk_playlistmovie_proplayer FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER),
    CONSTRAINT fk_playlistmovie_hero FOREIGN KEY (ID_HERO) REFERENCES HEROES(ID_HERO)
);

