CREATE TABLE IF NOT EXISTS TUMBLR (
    ID_HERO INTEGER NOT NULL,
    "description" VARCHAR(1000),
    HASH_TUMBLR VARCHAR(64) NOT NULL,
    "image" BYTEA,
    CONSTRAINT fk_tumblr_hero FOREIGN KEY (ID_HERO) REFERENCES HEROES(ID_HERO),
    PRIMARY KEY (ID_HERO, HASH_TUMBLR)
);