CREATE TABLE IF NOT EXISTS PLAYLIST (
    ID_PLAYLIST VARCHAR(50) NOT NULL,
    ID_YOUTUBE VARCHAR(50) NOT NULL,
    ID_GAME INTEGER,
    TITLE VARCHAR(100) NOT NULL,
    "description" VARCHAR(1000),
    REGISTER_DATE DATE NOT NULL,
    CONSTRAINT fk_playlist_channel FOREIGN KEY (ID_YOUTUBE) REFERENCES CHANNEL(ID_YOUTUBE),
    CONSTRAINT fk_playlist_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_PLAYLIST)
);