CREATE TABLE IF NOT EXISTS PROPLAYERS_GAMES (
    ID_PROPLAYER INTEGER NOT NULL,
    ID_GAME INTEGER NOT NULL,
    REGISTER_DATE DATE NOT NULL,
    CONSTRAINT fk_proplayersgames_proplayer FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER),
    CONSTRAINT fk_proplayersgames_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_PROPLAYER, ID_GAME)
);
