CREATE TABLE IF NOT EXISTS TEAMS_GAME (
    ID_TEAM INTEGER NOT NULL,
    ID_GAME INTEGER,
    BANNER BYTEA,
    CONSTRAINT fk_teamsgame_team FOREIGN KEY (ID_TEAM) REFERENCES TEAMS(ID_TEAM),
    CONSTRAINT fk_teamsgame_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_TEAM, ID_GAME)
);