CREATE TABLE IF NOT EXISTS PROPLAYERS_HEROES (
    ID_PROPLAYER INTEGER NOT NULL,
    ID_HERO INTEGER NOT NULL,
    REGISTER_DATE DATE NOT NULL,
    CONSTRAINT fk_proplayersheroes_proplayer FOREIGN KEY (ID_PROPLAYER) REFERENCES PROPLAYERS(ID_PROPLAYER),
    CONSTRAINT fk_proplayersheroes_hero FOREIGN KEY (ID_HERO) REFERENCES HEROES(ID_HERO),
    PRIMARY KEY (ID_PROPLAYER, ID_HERO)
);
