CREATE TABLE IF NOT EXISTS CHANNEL_HISTORIC (
    ID_YOUTUBE VARCHAR(50) NOT NULL,
    VIEWS INTEGER NOT NULL,
    SUBSCRIBERS INTEGER NOT NULL,
    REGISTER_DATE DATE NOT NULL,
    CONSTRAINT fk_channelhistoric_channel FOREIGN KEY (ID_YOUTUBE) REFERENCES CHANNEL(ID_YOUTUBE),
    PRIMARY KEY (ID_YOUTUBE, REGISTER_DATE)
);