CREATE TABLE IF NOT EXISTS HEROES (
    ID_HERO SERIAL,
    "name" VARCHAR(50) NOT NULL,
    ID_GAME INTEGER,
    "description" VARCHAR(1000),
    "image" BYTEA,
    CONSTRAINT fk_heroes_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_HERO)
);
