CREATE TABLE IF NOT EXISTS CHANNEL_IMAGES (
    ID_YOUTUBE VARCHAR(30) NOT NULL,
    LOGO BYTEA,
    BANNER BYTEA,
    VANITY BYTEA,
    CONSTRAINT fk_channelimages_channel FOREIGN KEY (ID_YOUTUBE) REFERENCES CHANNEL(ID_YOUTUBE),
    PRIMARY KEY (ID_YOUTUBE)
);