CREATE TABLE IF NOT EXISTS ITENS (
    ID_ITEM SERIAL,
    "name" VARCHAR(50) NOT NULL,
    ID_GAME INTEGER NOT NULL,
    "description" VARCHAR(1000),
    "VALUE" INTEGER NOT NULL,
    CONSTRAINT fk_itens_game FOREIGN KEY (ID_GAME) REFERENCES GAMES(ID_GAME),
    PRIMARY KEY (ID_ITEM)
);